name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_a5f195ca-f173-4d27-81f4-2ed78ceaedf5
          GH_TOKEN: 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
          COMMIT_BY_ME: true
          COMMIT_USERNAME: JayEsEichi
          COMMIT_EMAIL: wlstpgns51@naver.com
          SHOW_LOC_CHART: false
          SHOW_UPDATED_DATE: false
          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_SHORT_INFO: false
          SYMBOL_VERSION: 2
          LOCALE: ko
