name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: JayEsEichi/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_a5f195ca-f173-4d27-81f4-2ed78ceaedf5
          GH_TOKEN: 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
          LOCALE: "ko"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
